### ISSUE TITLE
Proposal to use current color scheme / theme if skin does not provide it

### ISSUE THREAD

**Issue by ghost** [deathaxe/sublime-skins#8]
When I create skins for adaptive themes I don't want to change the color scheme. Maybe it make sense to provide something like `"color_scheme": "auto"`. @deathaxe, what do you think?

**Comment by deathaxe** [comment]
I am a bit confused. If I use Adaptive theme, I don't change theme but only color_schemes.  Why changing an adaptive theme without color scheme?

You want to create several skins, which altogether apply the theme and set different options but without changing the color scheme?

Would basically work if the skin validation is modified in a way check for at least a valid theme or color scheme to be available instead of both together. But Skins was supposed to be used to set both together with one command. _Menu Theme Switcher_ was intended to be used to change theme or color scheme separately.

**Comment by ghost** [comment]
> You want to create several skins, which altogether apply the theme and set different options but without changing the color scheme?

Exactly! :wink:  

> But Skins was supposed to be used to set both together with one command.

I understand this, but in some cases it isn't necessary to change them both at once.

> Would basically work if the skin validation is modified in a way check for at least a valid theme or color scheme to be available instead of both together.

It would be great :heart:
